In [1]:
# Let's read in our document-term matrix
import pandas as pd
import pickle

data = pd.read_pickle('dtm.pkl')
data

,abandoned,abilities,ability,ablaze,able,abominable,abomination,abominations,absolutely,academy,...,youve,yowza,yuck,yup,zealots,zero,zombies,zone,zurich,ça
episode 1,1,0,0,0,0,0,0,0,0,1,...,4,0,0,0,1,1,0,0,0,1
episode 2,0,0,1,0,1,0,0,0,0,0,...,4,0,0,0,0,0,0,0,0,0
episode 3,0,1,1,1,2,0,0,1,0,2,...,1,0,2,0,0,0,1,0,0,0
episode 4,0,0,1,0,1,1,0,0,1,0,...,3,0,0,0,0,2,0,2,0,0
episode 5,1,1,1,0,0,0,0,0,0,0,...,4,0,0,0,0,0,0,0,0,0
episode 6,0,0,2,0,1,0,0,0,0,0,...,2,0,0,0,0,0,0,0,0,0
episode 7,0,0,0,0,1,0,0,0,0,0,...,12,1,0,0,0,0,0,0,1,0
episode 8,0,0,1,0,1,0,1,1,0,0,...,4,0,0,1,0,1,0,0,0,0

In [2]:
# Import the necessary modules for LDA with gensim
# Terminal / Anaconda Navigator: conda install -c conda-forge gensim
from gensim import matutils, models
import scipy.sparse

# import logging
# logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)

In [3]:
# One of the required inputs is a term-document matrix
tdm = data.transpose()
tdm.head()

,episode 1,episode 2,episode 3,episode 4,episode 5,episode 6,episode 7,episode 8
abandoned,1,0,0,0,1,0,0,0
abilities,0,0,1,0,1,0,0,0
ability,0,1,1,1,1,2,0,1
ablaze,0,0,1,0,0,0,0,0
able,0,1,2,1,0,1,1,1

In [4]:
# We're going to put the term-document matrix into a new gensim format, from df --> sparse matrix --> gensim corpus
sparse_counts = scipy.sparse.csr_matrix(tdm)
corpus = matutils.Sparse2Corpus(sparse_counts)

In [5]:
# Gensim also requires dictionary of the all terms and their respective location in the term-document matrix
cv = pickle.load(open("cv.pkl", "rb"))
id2word = dict((v, k) for k, v in cv.vocabulary_.items())

Now that we have the corpus (term-document matrix) and id2word (dictionary of location: term), we need to specify two other parameters - the number of topics and the number of passes. Let's start the number of topics at 2, see if the results make sense, and increase the number from there.

In [6]:
# Now that we have the corpus (term-document matrix) and id2word (dictionary of location: term),
# we need to specify two other parameters as well - the number of topics and the number of passes
lda = models.LdaModel(corpus=corpus, id2word=id2word, num_topics=2, passes=10)
lda.print_topics()

[(0,
  '0.010*"wednesday" + 0.009*"im" + 0.007*"know" + 0.006*"tyler" + 0.006*"hyde" + 0.006*"just" + 0.006*"dont" + 0.004*"youre" + 0.004*"like" + 0.004*"thing"'),
 (1,
  '0.010*"im" + 0.009*"know" + 0.008*"wednesday" + 0.008*"dont" + 0.008*"like" + 0.007*"youre" + 0.006*"just" + 0.005*"want" + 0.005*"did" + 0.005*"right"')]

In [7]:
# LDA for num_topics = 3
lda = models.LdaModel(corpus=corpus, id2word=id2word, num_topics=3, passes=10)
lda.print_topics()

[(0,
  '0.013*"im" + 0.012*"wednesday" + 0.008*"dont" + 0.007*"like" + 0.007*"know" + 0.007*"youre" + 0.006*"just" + 0.005*"come" + 0.005*"thing" + 0.005*"going"'),
 (1,
  '0.000*"know" + 0.000*"im" + 0.000*"dont" + 0.000*"wednesday" + 0.000*"like" + 0.000*"just" + 0.000*"youre" + 0.000*"want" + 0.000*"thing" + 0.000*"need"'),
 (2,
  '0.010*"know" + 0.009*"im" + 0.008*"dont" + 0.008*"like" + 0.007*"just" + 0.007*"wednesday" + 0.006*"youre" + 0.006*"right" + 0.005*"want" + 0.005*"did"')]

In [8]:
# LDA for num_topics = 4
lda = models.LdaModel(corpus=corpus, id2word=id2word, num_topics=4, passes=10)
lda.print_topics()

[(0,
  '0.001*"wednesday" + 0.000*"dont" + 0.000*"im" + 0.000*"know" + 0.000*"like" + 0.000*"just" + 0.000*"youre" + 0.000*"right" + 0.000*"didnt" + 0.000*"thing"'),
 (1,
  '0.001*"im" + 0.000*"wednesday" + 0.000*"know" + 0.000*"dont" + 0.000*"youre" + 0.000*"just" + 0.000*"like" + 0.000*"did" + 0.000*"nevermore" + 0.000*"want"'),
 (2,
  '0.013*"im" + 0.011*"wednesday" + 0.010*"know" + 0.009*"dont" + 0.009*"like" + 0.008*"just" + 0.007*"youre" + 0.005*"right" + 0.005*"want" + 0.005*"come"'),
 (3,
  '0.005*"nevermore" + 0.004*"school" + 0.002*"youre" + 0.002*"love" + 0.002*"way" + 0.002*"im" + 0.002*"rien" + 0.002*"luck" + 0.002*"boys" + 0.002*"rest"')]

These topics aren't looking too great. We've tried modifying our parameters. Let's try modifying our terms list as well.

## Topic Modeling - Attempt #2 (Nouns Only)

One popular trick is to look only at terms that are from one part of speech (only nouns, only adjectives, etc.). Check out the UPenn tag set: https://www.ling.upenn.edu/courses/Fall_2003/ling001/penn_treebank_pos.html.

In [9]:
# Let's create a function to pull out nouns from a string of text
from nltk import word_tokenize, pos_tag

def nouns(text):
    '''Given a string of text, tokenize the text and pull out only the nouns.'''
    is_noun = lambda pos: pos[:2] == 'NN'
    tokenized = word_tokenize(text)
    all_nouns = [word for (word, pos) in pos_tag(tokenized) if is_noun(pos)] 
    return ' '.join(all_nouns)

In [10]:
# Read in the cleaned data, before the CountVectorizer step
data_clean = pd.read_pickle('data_clean.pkl')
data_clean

                                                  transcript
episode 1   wednesday addams a highschool student finds h...
episode 2   wednesday convinces a skeptical sheriff galpi...
episode 3   wednesday finds herself tied up and surrounde...
episode 4   wednesday and thing break into the coroners o...
episode 5    years ago gomez is arrested on suspicion of ...
episode 6   wednesday attempts to summon goody an old anc...
episode 7   at mayor walkers funeral wednesday notices a ...
episode 8   wednesday and her classmates lure tyler into ...

In [11]:
# Apply the nouns function to the transcripts to filter only on nouns
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
data_nouns = pd.DataFrame(data_clean.transcript.apply(nouns))
data_nouns

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\singl\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\singl\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

                                                  transcript
episode 1  student brother pugsley locker vision bullies ...
episode 2  sheriff galpin perpetrator murders fact monste...
episode 3  members students society bianca wednesday libr...
episode 4  wednesday thing break coroners office files mo...
episode 5  years gomez suspicion garrett gates time addam...
episode 6  wednesday attempts goody ancestor psychic surp...
episode 7  mayor walkers notices figure figure fester mon...
episode 8  wednesday classmates tyler confession wednesda...

In [12]:
# Create a new document-term matrix using only nouns
from sklearn.feature_extraction import text
from sklearn.feature_extraction.text import CountVectorizer

# Re-add the additional stop words since we are recreating the document-term matrix
add_stop_words = ['like', 'im', 'know', 'just', 'dont', 'thats', 'right', 'people',
                  'youre', 'got', 'gonna', 'time', 'think', 'yeah', 'said']
stop_words = list(text.ENGLISH_STOP_WORDS).append(add_stop_words)

# Recreate a document-term matrix with only nouns
cvn = CountVectorizer(stop_words=stop_words)
data_cvn = cvn.fit_transform(data_nouns.transcript)
data_dtmn = pd.DataFrame(data_cvn.toarray(), columns=cvn.get_feature_names_out())
data_dtmn.index = data_nouns.index
data_dtmn

,abilities,ability,abomination,abominations,academy,accident,accounts,accusations,act,action,...,youll,youre,yours,youve,yuck,zero,zombies,zone,zurich,ça
episode 1,0,0,0,0,1,1,0,0,0,0,...,4,17,0,4,0,1,0,0,0,1
episode 2,0,1,0,0,0,2,0,0,1,0,...,0,8,0,2,0,0,0,0,0,0
episode 3,1,1,0,1,1,0,0,0,0,0,...,1,14,0,1,1,0,1,0,0,0
episode 4,0,1,0,0,0,1,0,0,1,0,...,0,8,0,0,0,1,0,1,0,0
episode 5,1,1,0,0,0,2,1,0,0,0,...,0,7,0,2,0,0,0,0,0,0
episode 6,0,2,0,0,0,0,0,0,2,1,...,2,12,1,1,0,0,0,0,0,0
episode 7,0,0,0,0,0,0,0,0,0,0,...,2,6,0,3,0,0,0,0,1,0
episode 8,0,1,1,1,0,0,0,1,1,1,...,0,12,2,2,0,1,0,0,0,0

In [13]:
# Create the gensim corpus
corpusn = matutils.Sparse2Corpus(scipy.sparse.csr_matrix(data_dtmn.transpose()))

# Create the vocabulary dictionary
id2wordn = dict((v, k) for k, v in cvn.vocabulary_.items())

In [14]:
# Let's start with 2 topics
ldan = models.LdaModel(corpus=corpusn, num_topics=2, id2word=id2wordn, passes=10)
ldan.print_topics()

[(0,
  '0.010*"youre" + 0.009*"thing" + 0.008*"im" + 0.008*"wednesday" + 0.007*"monster" + 0.006*"time" + 0.005*"dont" + 0.005*"people" + 0.005*"school" + 0.005*"thats"'),
 (1,
  '0.008*"im" + 0.007*"wednesday" + 0.007*"thing" + 0.007*"youre" + 0.007*"time" + 0.007*"mother" + 0.007*"tyler" + 0.006*"father" + 0.006*"school" + 0.005*"way"')]

In [15]:
# Let's try topics = 3
ldan = models.LdaModel(corpus=corpusn, num_topics=3, id2word=id2wordn, passes=10)
ldan.print_topics()

[(0,
  '0.010*"youre" + 0.009*"school" + 0.008*"wednesday" + 0.008*"mother" + 0.007*"im" + 0.007*"dont" + 0.007*"way" + 0.007*"father" + 0.007*"time" + 0.007*"family"'),
 (1,
  '0.009*"crackstone" + 0.008*"youre" + 0.007*"monster" + 0.006*"house" + 0.006*"meeting" + 0.005*"im" + 0.005*"thing" + 0.005*"hes" + 0.005*"world" + 0.005*"joseph"'),
 (2,
  '0.011*"thing" + 0.011*"im" + 0.009*"wednesday" + 0.008*"youre" + 0.008*"monster" + 0.008*"tyler" + 0.007*"time" + 0.007*"hyde" + 0.006*"night" + 0.005*"thats"')]

In [16]:
# Let's try 4 topics
ldan = models.LdaModel(corpus=corpusn, num_topics=4, id2word=id2wordn, passes=10)
ldan.print_topics()

[(0,
  '0.012*"youre" + 0.009*"wednesday" + 0.009*"school" + 0.008*"thing" + 0.007*"im" + 0.007*"mother" + 0.007*"dont" + 0.006*"way" + 0.006*"time" + 0.006*"people"'),
 (1,
  '0.010*"im" + 0.009*"thing" + 0.008*"wednesday" + 0.007*"dance" + 0.007*"youre" + 0.006*"monster" + 0.005*"something" + 0.005*"night" + 0.005*"goo" + 0.005*"rowan"'),
 (2,
  '0.001*"youre" + 0.001*"school" + 0.001*"wednesday" + 0.001*"im" + 0.001*"dont" + 0.001*"thing" + 0.001*"people" + 0.001*"way" + 0.001*"time" + 0.001*"thats"'),
 (3,
  '0.009*"youre" + 0.009*"im" + 0.009*"time" + 0.008*"thing" + 0.008*"monster" + 0.008*"wednesday" + 0.008*"tyler" + 0.007*"hyde" + 0.006*"father" + 0.006*"gates"')]

## Topic Modeling - Attempt #3 (Nouns and Adjectives)

In [17]:
# Let's create a function to pull out nouns and adjectives from a string of text
def nouns_adj(text):
    '''Given a string of text, tokenize the text and pull out only the nouns and adjectives.'''
    is_noun_adj = lambda pos: pos[:2] == 'NN' or pos[:2] == 'JJ'
    tokenized = word_tokenize(text)
    nouns_adj = [word for (word, pos) in pos_tag(tokenized) if is_noun_adj(pos)] 
    return ' '.join(nouns_adj)

In [18]:
# Apply the nouns function to the transcripts to filter only on nouns and adjectives
data_nouns_adj = pd.DataFrame(data_clean.transcript.apply(nouns_adj))
data_nouns_adj

                                                  transcript
episode 1  wednesday highschool student brother pugsley l...
episode 2  wednesday skeptical sheriff galpin perpetrator...
episode 3  wednesday members elite students society bianc...
episode 4  wednesday thing break coroners office files mo...
episode 5  years gomez suspicion garrett gates present ti...
episode 6  wednesday attempts goody old ancestor fellow p...
episode 7  mayor walkers funeral wednesday notices lurkin...
episode 8  wednesday classmates tyler forest confession w...

In [19]:
# Create a new document-term matrix using only nouns and adjectives, also remove common words with max_df
cvna = CountVectorizer(stop_words=stop_words, max_df=.8)
data_cvna = cvna.fit_transform(data_nouns_adj.transcript)
data_dtmna = pd.DataFrame(data_cvna.toarray(), columns=cvna.get_feature_names_out())
data_dtmna.index = data_nouns_adj.index
data_dtmna

,abilities,ability,able,abominable,abomination,abominations,academy,accept,accident,accounts,...,youll,young,yours,youthful,yuck,zero,zombies,zone,zurich,ça
episode 1,0,0,0,0,0,0,1,1,1,0,...,5,0,0,0,0,1,0,0,0,1
episode 2,0,1,1,0,0,0,0,0,2,0,...,0,0,0,0,0,0,0,0,0,0
episode 3,1,1,2,0,0,1,2,0,0,0,...,1,1,0,0,2,0,1,0,0,0
episode 4,0,1,1,1,0,0,0,0,1,0,...,0,0,0,0,0,1,0,1,0,0
episode 5,1,1,0,0,0,0,0,0,2,1,...,0,0,0,1,0,0,0,0,0,0
episode 6,0,2,1,0,0,0,0,0,0,0,...,2,0,1,0,0,0,0,0,0,0
episode 7,0,0,1,0,0,0,0,0,0,0,...,3,1,0,0,0,0,0,0,1,0
episode 8,0,1,1,0,1,1,0,0,0,0,...,0,1,2,0,0,1,0,0,0,0

In [20]:
# Create the gensim corpus
corpusna = matutils.Sparse2Corpus(scipy.sparse.csr_matrix(data_dtmna.transpose()))

# Create the vocabulary dictionary
id2wordna = dict((v, k) for k, v in cvna.vocabulary_.items())

In [21]:
# Let's start with 2 topics
ldana = models.LdaModel(corpus=corpusna, num_topics=2, id2word=id2wordna, passes=10)
ldana.print_topics()

[(0,
  '0.006*"dance" + 0.005*"raven" + 0.005*"eugene" + 0.005*"birthday" + 0.004*"gates" + 0.004*"goo" + 0.004*"mayor" + 0.004*"goody" + 0.003*"god" + 0.003*"date"'),
 (1,
  '0.005*"hyde" + 0.004*"gates" + 0.004*"crackstone" + 0.003*"garrett" + 0.003*"bianca" + 0.003*"much" + 0.003*"parents" + 0.002*"wait" + 0.002*"kinbott" + 0.002*"jericho"')]

In [22]:
# Let's try 3 topics
ldana = models.LdaModel(corpus=corpusna, num_topics=3, id2word=id2wordna, passes=10)
ldana.print_topics()

[(0,
  '0.009*"crackstone" + 0.005*"hyde" + 0.004*"house" + 0.004*"pilgrim" + 0.004*"meeting" + 0.004*"joseph" + 0.003*"goody" + 0.003*"god" + 0.003*"gates" + 0.003*"woods"'),
 (1,
  '0.006*"hyde" + 0.006*"gates" + 0.006*"dance" + 0.005*"raven" + 0.005*"mayor" + 0.005*"eugene" + 0.004*"birthday" + 0.004*"date" + 0.004*"goody" + 0.004*"kinbott"'),
 (2,
  '0.006*"garrett" + 0.004*"parents" + 0.004*"murder" + 0.003*"cup" + 0.003*"weekend" + 0.003*"bianca" + 0.003*"scales" + 0.003*"gates" + 0.003*"full" + 0.003*"poe"')]

In [23]:
# Let's try 4 topics
ldana = models.LdaModel(corpus=corpusna, num_topics=4, id2word=id2wordna, passes=10)
ldana.print_topics()

[(0,
  '0.005*"dance" + 0.005*"crackstone" + 0.005*"eugene" + 0.004*"raven" + 0.004*"woods" + 0.004*"poe" + 0.004*"cup" + 0.003*"goo" + 0.003*"bianca" + 0.003*"meeting"'),
 (1,
  '0.000*"dance" + 0.000*"gates" + 0.000*"crackstone" + 0.000*"eugene" + 0.000*"god" + 0.000*"hyde" + 0.000*"raven" + 0.000*"house" + 0.000*"mayor" + 0.000*"bianca"'),
 (2,
  '0.007*"garrett" + 0.007*"gates" + 0.004*"parents" + 0.004*"goody" + 0.004*"best" + 0.004*"weekend" + 0.004*"birthday" + 0.003*"murder" + 0.003*"full" + 0.003*"week"'),
 (3,
  '0.016*"hyde" + 0.007*"gates" + 0.006*"kinbott" + 0.006*"laurel" + 0.005*"diary" + 0.005*"uncle" + 0.004*"eugene" + 0.004*"fester" + 0.004*"crackstone" + 0.004*"friend"')]

## Identify Topics in Each Document

Out of the 9 topic models we looked at, the nouns and adjectives, 4 topic one made the most sense. So let's pull that down here and run it through some more iterations to get more fine-tuned topics.

In [24]:
# Our final LDA model (for now)
ldana = models.LdaModel(corpus=corpusna, num_topics=4, id2word=id2wordna, passes=80)
ldana.print_topics()

[(0,
  '0.007*"dance" + 0.005*"crackstone" + 0.005*"house" + 0.005*"raven" + 0.004*"birthday" + 0.004*"goody" + 0.004*"eugene" + 0.004*"mayor" + 0.004*"god" + 0.004*"gates"'),
 (1,
  '0.014*"hyde" + 0.007*"diary" + 0.006*"kinbott" + 0.006*"uncle" + 0.006*"fester" + 0.005*"dr" + 0.005*"laurel" + 0.005*"gates" + 0.004*"master" + 0.004*"mayor"'),
 (2,
  '0.007*"garrett" + 0.006*"gates" + 0.004*"bianca" + 0.004*"eugene" + 0.004*"hyde" + 0.004*"cup" + 0.003*"weekend" + 0.003*"poe" + 0.003*"wait" + 0.003*"much"'),
 (3,
  '0.003*"parents" + 0.003*"week" + 0.003*"rest" + 0.003*"murder" + 0.003*"youll" + 0.002*"perfect" + 0.002*"please" + 0.002*"wednesdays" + 0.002*"course" + 0.002*"session"')]

These four topics look pretty decent. Let's settle on these for now.
* Topic 0: dance
* Topic 1: characters
* Topic 2: gates
* Topic 3: parents,time

In [25]:
# Let's take a look at which topics each transcript contains
corpus_transformed = ldana[corpusna]
list(zip([a for [(a,b)] in corpus_transformed], data_dtmna.index))

[(3, 'episode 1'),
 (2, 'episode 2'),
 (0, 'episode 3'),
 (0, 'episode 4'),
 (2, 'episode 5'),
 (0, 'episode 6'),
 (1, 'episode 7'),
 (2, 'episode 8')]

In [26]:
add_stop_words = ['like', 'im', 'know', 'just', 'dont', 'thats', 'right', 'people',
                  'youre', 'got', 'gonna', 'time', 'think', 'yeah', 'said', 'fuck', 'fucking','fck','sex']
stop_words = list(text.ENGLISH_STOP_WORDS).append(add_stop_words)
cvna = CountVectorizer(stop_words=stop_words, max_df=.8)
data_cvna = cvna.fit_transform(data_nouns_adj.transcript)
data_dtmna = pd.DataFrame(data_cvna.toarray(), columns=cvna.get_feature_names_out())
data_dtmna.index = data_nouns_adj.index
data_dtmna

,abilities,ability,able,abominable,abomination,abominations,academy,accept,accident,accounts,...,youll,young,yours,youthful,yuck,zero,zombies,zone,zurich,ça
episode 1,0,0,0,0,0,0,1,1,1,0,...,5,0,0,0,0,1,0,0,0,1
episode 2,0,1,1,0,0,0,0,0,2,0,...,0,0,0,0,0,0,0,0,0,0
episode 3,1,1,2,0,0,1,2,0,0,0,...,1,1,0,0,2,0,1,0,0,0
episode 4,0,1,1,1,0,0,0,0,1,0,...,0,0,0,0,0,1,0,1,0,0
episode 5,1,1,0,0,0,0,0,0,2,1,...,0,0,0,1,0,0,0,0,0,0
episode 6,0,2,1,0,0,0,0,0,0,0,...,2,0,1,0,0,0,0,0,0,0
episode 7,0,0,1,0,0,0,0,0,0,0,...,3,1,0,0,0,0,0,0,1,0
episode 8,0,1,1,0,1,1,0,0,0,0,...,0,1,2,0,0,1,0,0,0,0

In [27]:
# Create the gensim corpus
corpusna = matutils.Sparse2Corpus(scipy.sparse.csr_matrix(data_dtmna.transpose()))

# Create the vocabulary dictionary
id2wordna = dict((v, k) for k, v in cvna.vocabulary_.items())

In [28]:
ldana = models.LdaModel(corpus=corpusna, num_topics=8, id2word=id2wordna, passes=15, alpha='auto', eta='auto', chunksize=2000, minimum_probability=0.002)
ldana.print_topics()

[(0,
  '0.000*"eugene" + 0.000*"dance" + 0.000*"gates" + 0.000*"hyde" + 0.000*"raven" + 0.000*"best" + 0.000*"garrett" + 0.000*"sorry" + 0.000*"date" + 0.000*"woods"'),
 (1,
  '0.012*"crackstone" + 0.007*"house" + 0.007*"meeting" + 0.007*"pilgrim" + 0.007*"joseph" + 0.005*"jericho" + 0.004*"visions" + 0.004*"history" + 0.004*"witch" + 0.004*"big"'),
 (2,
  '0.010*"hyde" + 0.005*"diary" + 0.005*"cup" + 0.005*"kinbott" + 0.005*"uncle" + 0.005*"poe" + 0.004*"mayor" + 0.004*"fester" + 0.004*"scales" + 0.004*"dr"'),
 (3,
  '0.013*"hyde" + 0.009*"crackstone" + 0.008*"gates" + 0.006*"wait" + 0.006*"goody" + 0.006*"laurel" + 0.006*"blood" + 0.005*"eugene" + 0.005*"principal" + 0.005*"station"'),
 (4,
  '0.014*"dance" + 0.012*"eugene" + 0.011*"raven" + 0.009*"goo" + 0.007*"date" + 0.005*"sorry" + 0.004*"god" + 0.004*"victims" + 0.004*"look" + 0.003*"cave"'),
 (5,
  '0.004*"parents" + 0.003*"youll" + 0.003*"murder" + 0.003*"week" + 0.003*"rest" + 0.003*"course" + 0.003*"look" + 0.003*"full" + 0.003*"wednesdays" + 0.003*"everyone"'),
 (6,
  '0.000*"scales" + 0.000*"poe" + 0.000*"cup" + 0.000*"murder" + 0.000*"bianca" + 0.000*"gates" + 0.000*"dance" + 0.000*"eugene" + 0.000*"parents" + 0.000*"woods"'),
 (7,
  '0.012*"garrett" + 0.011*"gates" + 0.007*"goody" + 0.006*"birthday" + 0.006*"weekend" + 0.005*"best" + 0.005*"mayor" + 0.005*"happy" + 0.004*"walker" + 0.004*"parents"')]

In [29]:
corpus_transformed = ldana[corpusna]
list(zip([a for [(a,b)] in corpus_transformed], data_dtmna.index))

ValueError: too many values to unpack (expected 1)

In [ ]:
# Let's create a function to pull out nouns,verbs and adjectives from a string of text
def nouns_adj(text):
    '''Given a string of text, tokenize the text and pull out only the nouns and adjectives.'''
    is_noun_adj = lambda pos: pos[:2] == 'NN' or pos[:2] == 'VB' or pos[:2] == 'JJ'
    tokenized = word_tokenize(text)
    nouns_adj = [word for (word, pos) in pos_tag(tokenized) if is_noun_adj(pos)] 
    return ' '.join(nouns_adj)

In [30]:
data_nouns_adj = pd.DataFrame(data_clean.transcript.apply(nouns_adj))
data_nouns_adj

                                                  transcript
episode 1  wednesday highschool student brother pugsley l...
episode 2  wednesday skeptical sheriff galpin perpetrator...
episode 3  wednesday members elite students society bianc...
episode 4  wednesday thing break coroners office files mo...
episode 5  years gomez suspicion garrett gates present ti...
episode 6  wednesday attempts goody old ancestor fellow p...
episode 7  mayor walkers funeral wednesday notices lurkin...
episode 8  wednesday classmates tyler forest confession w...

In [31]:
cvna = CountVectorizer(stop_words=stop_words, max_df=.8)
data_cvna = cvna.fit_transform(data_nouns_adj.transcript)
data_dtmna = pd.DataFrame(data_cvna.toarray(), columns=cvna.get_feature_names_out())
data_dtmna.index = data_nouns_adj.index
data_dtmna

,abilities,ability,able,abominable,abomination,abominations,academy,accept,accident,accounts,...,youll,young,yours,youthful,yuck,zero,zombies,zone,zurich,ça
episode 1,0,0,0,0,0,0,1,1,1,0,...,5,0,0,0,0,1,0,0,0,1
episode 2,0,1,1,0,0,0,0,0,2,0,...,0,0,0,0,0,0,0,0,0,0
episode 3,1,1,2,0,0,1,2,0,0,0,...,1,1,0,0,2,0,1,0,0,0
episode 4,0,1,1,1,0,0,0,0,1,0,...,0,0,0,0,0,1,0,1,0,0
episode 5,1,1,0,0,0,0,0,0,2,1,...,0,0,0,1,0,0,0,0,0,0
episode 6,0,2,1,0,0,0,0,0,0,0,...,2,0,1,0,0,0,0,0,0,0
episode 7,0,0,1,0,0,0,0,0,0,0,...,3,1,0,0,0,0,0,0,1,0
episode 8,0,1,1,0,1,1,0,0,0,0,...,0,1,2,0,0,1,0,0,0,0

In [32]:
# Create the gensim corpus
corpusna = matutils.Sparse2Corpus(scipy.sparse.csr_matrix(data_dtmna.transpose()))

# Create the vocabulary dictionary
id2wordna = dict((v, k) for k, v in cvna.vocabulary_.items())

In [33]:
ldana = models.LdaModel(corpus=corpusna, num_topics=5,alpha='auto', eta='auto',chunksize=1000, minimum_probability=0.002,id2word=id2wordna, passes=15)
ldana.print_topics()

[(0,
  '0.000*"hyde" + 0.000*"garrett" + 0.000*"gates" + 0.000*"parents" + 0.000*"murder" + 0.000*"best" + 0.000*"mayor" + 0.000*"dance" + 0.000*"much" + 0.000*"course"'),
 (1,
  '0.010*"hyde" + 0.007*"crackstone" + 0.006*"gates" + 0.006*"eugene" + 0.005*"wait" + 0.005*"goody" + 0.005*"laurel" + 0.005*"blood" + 0.004*"god" + 0.004*"station"'),
 (2,
  '0.000*"hyde" + 0.000*"gates" + 0.000*"crackstone" + 0.000*"dance" + 0.000*"eugene" + 0.000*"mayor" + 0.000*"house" + 0.000*"best" + 0.000*"wait" + 0.000*"raven"'),
 (3,
  '0.006*"gates" + 0.005*"dance" + 0.005*"garrett" + 0.005*"mayor" + 0.004*"hyde" + 0.004*"eugene" + 0.004*"crackstone" + 0.004*"goody" + 0.004*"house" + 0.004*"raven"'),
 (4,
  '0.005*"cup" + 0.004*"scales" + 0.004*"poe" + 0.004*"bianca" + 0.003*"everyone" + 0.003*"murder" + 0.003*"parents" + 0.003*"look" + 0.003*"roommate" + 0.003*"wait"')]

In [34]:
corpus_transformed = ldana[corpusna]
list(zip([a for [(a,b)] in corpus_transformed], data_dtmna.index))

[(4, 'episode 1'),
 (4, 'episode 2'),
 (3, 'episode 3'),
 (3, 'episode 4'),
 (3, 'episode 5'),
 (3, 'episode 6'),
 (3, 'episode 7'),
 (1, 'episode 8')]